[package]
name = "trojan-oxide"
version = "0.1.0"
authors = ["3andne <3andne@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio={version = "1.2", features = ["full"]}
clap = "2.33.3"
anyhow = { version = "1.0.41" }
tracing = "0.1.26"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.19"
futures = "0.3"
err-derive = "0.3.0"
quinn = "0.7.2"
quinn-proto = "0.7.3"
directories = "3.0"
structopt = "0.3.21"
rcgen = "0.8.11"
# rustls = "0.19.1"
sha2 = "0.9.5"
#webpki = "0.22"
webpki-roots = "0.21"
bytes = "1.0.1"
pin-project-lite = "0.2.7"
lazy_static = "1.4.0"
tokio-rustls = "0.22.0"
rustls-native-certs = "*"
trust-dns-resolver = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_simd"
harness = false
