[package]
name = "trojan-oxide"
version = "0.1.0"
authors = ["3andne <3andne@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#async-std = "1"
#async-tls = "*"
#hyper = "*"
tokio={version = "1", features = ["full"]}
bytes = "1"
clap = "2"
anyhow = { version = "1" }
tracing = "0.1.25"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2"
futures = "0.3"
err-derive = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_simd"
harness = false

