[package]
name = "trojan-oxide"
version = "0.1.0"
authors = ["3andne <3andne@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1"
async-tls = "*"
hyper = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_simd"
harness = false

